services:
  #  MongoDB (数据库)
  mongo:
    image: mongo:latest
    container_name: demo-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
